- name: Patch Nginx on Kali Linux
  hosts: localhost
  become: yes

  tasks:
    - name: Remove outdated Nginx (if installed manually)
      file:
        path: /usr/local/nginx
        state: absent

    - name: Ensure system package lists are updated
      apt:
        update_cache: yes

    - name: Install latest Nginx
      apt:
        name: nginx
        state: latest

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
